baseURL = "https://nathanaelhoun.fr/"
title = "Nathanaël Houn Personal Website"

languageCode = "en"
defaultcontentlanguage = "en"

theme = "hugo-developer-portfolio"

paginate = 20
canonifyurls = false
publishDir = "docs"

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    home = "Home"

    author = "Nathanaël Houn"
    avatarurl = "/images/nathanael.jpg"
    favicon_32 = "/images/favicon-32x32.ico"

    [params.contact]
        # TODO !!
        formAction = "" # Add your formspree URL here to get emails

    [params.footer]
        email = "contact[at]nathanaelhoun[dot]fr"
        address = "France"

    [params.plugins]
        [[params.plugins.css]]
        URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/css/uikit.min.css"
        [[params.plugins.js]]
        URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit.min.js"
        [[params.plugins.js]]
        URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit-icons.min.js"

    [menu] # It is possible to change the menu too.
        [[menu.main]]
            name = "About"
            url = "about"
#        [[menu.main]]
#            name = "Blog"
#            url = "posts"
        [[menu.main]]
            name = "Portfolio"
            url  = "portfolio"
        [[menu.main]]
            name = "Contact"
            URL = "contact"