baseURL: https://nathanaelhoun-fr.onrender.com/
title: Nathanaël Houn Personal Website

languageCode: en
defaultcontentlanguage: en

sitemap:
  changefreq: "monthly"
  priority: 0.5
  filename: "sitemap.xml"
